var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "  xs                                                                        sx  ",
   "  xs                        o                                               sx  ",
   "  xs                                                o                       sx  ",
   "  xs                      xxxxx      e    x                        s        sx  ",
   "  x                o      sssss      xx             x      e       s         x  ",
   "  x                                                xxx     xx    xxsxx       x  ",
   "  x              xxxxx          e           sxxs                   s         x  ",
   "  x                                                                s       o x  ",
   "  x        e      xx          xxxxx              x!!x              s         x  ",
   "  x     xxxxx                                    xxxx                     xxxx  ",
   "  x o    sss                                                                 x  ",
   "  x                     o       o          s            o                r   x  ",
   "  xxxxx               xxxxx              xxxxx               x      e        x  ",
   "  x                                        o                 x      x   xxx  x  ",
   "  x  @      x    x   e      x       x      e        x        x      x!!!!!!!!x  ",
   "  xxxxxxxxxxxx!!xxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxx  ",
   "             x!!x             x!!!x                  x!!!!!x                    ",
   "             x!!x             x!!!x                  x!!!!!x                    ",
   "             x!!x             x!!!x                  xxxxxxx                    ",
   "             xxxx             xxxxx                                             ",
   "                                                                                ",
   "                                                                                "],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!xvxxxxxxxxxxxvxxxxxxxxxxxxvxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!",
   "!!!x                                                       xsssssssssssss                  x      =      x!!!",
   "!!!x                                                       xs                                            x!!!",
   "!!!x               o              o                        xs                   ooooo                    x!!!",
   "!!!x     o                                       o         xs                                            x!!!",
   "!!!x                   |              |                    xs                                            x!!!",
   "!!!xx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xs               sxxxxxxxxxxxxxxx             x!!!",
   "!!!x       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           xs         xxx   sx!!!!!!!!!!!!!x       =     x!!!",
   "!!!x o     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           xs   o           sx!!!!!!!!!!!!!x             x!!!",
   "!!!x       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     e     xs               sx!!!!!!!!!!!!!x   o         x!!!",
   "!!!xxx     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           xs               sx!!!!!!!!!!!!!x             x!!!",
   "!!!x       x!!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!x           xs   xx          sx!!!!!!!!!!!!!x       =     x!!!",
   "!!!x     o x!!!!!!!x                  x!!!!!!!!x           xs               sx!!!!!!!!!!!!!x             x!!!",
   "!!!x       x!!!!!!!x         e        x!!!!!!!!x        xxxxs               sx!!!!!!!!!!!!!x   o         x!!!",
   "!!!x     xxx!!!!!!!x                  x!!!!!!!!x           xs               sx!!!!!!!!!!!!!x             x!!!",
   "!!!x       x!!!!!!!x         =        x!!!!!!!!x           xs         xxx   sx!!!!!!!!!!!!!x       =     x!!!",
   "!!!x o     x!!!!!!!x                  x!!!!!!!!x     e     xs   o           sx!!!!!!!!!!!!!x             x!!!",
   "!!!x       x!!!!!!!xx  |     e    |  xx!!!!!!!!x           xs               sx!!!!!!!!!!!!!x   o         x!!!",
   "!!!xxx     x!!!!!!!x                  x!!!!!!!!x           xs               sx!!!!!!!!!!!!!x             x!!!",
   "!!!x       x!!!!!!!x         =        x!!!!!!!!x           xs   xx          sx!!!!!!!!!!!!!x       =     x!!!",
   "!!!x     o x!!!!!!!x                  x!!!!!!!!xxxxx       xs               sx!!!!!!!!!!!!!x             x!!!",
   "!!!x       x!!!!!!!x         e        x!!!!!!!!x           xs               sx!!!!!!!!!!!!!x   o         x!!!",
   "!!!x     xxx!!!!!!!x                  x!!!!!!!!x           xs               sx!!!!!!!!!!!!!x             x!!!",
   "!!!x       x!!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!x     e     xs         xxx   sx!!!!!!!!!!!!!x             x!!!",
   "!!!x   @   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           xs               sx!!!!!!!!!!!!!x          r  x!!!",
   "!!!x       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                            sx!!!!!!!!!!!!!x             x!!!",
   "!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                            sx!!!!!!!!!!!!!x             x!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxxxx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                    r                                                         ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                            !!                                                          x  ",
   "  x                                          !!xx!!xxx!!xx                                                 x  ",
   "  x     =      =     =       ssssssssss   e !!x!!!!!!!!!!!x       o                                        x  ",
   "  x          e               =             !!x!!!!!!!!!!!!!x                                               x  ",
   "  x      sssssssss      e          e      !!x!!!!!!!!!!!!!!!x               o                              x  ",
   "  x   =        =         =        =      !!x!!!!!!!!!!!!!!!!!x   xxx                                       x  ",
   "  x    e    e     e    xxxxxxxx    e    !!x!!!!!!!!!!!!!!!!!!!x  sss       xx                              x  ",
   "  x                                    !!x!!!!x!!!xxxxvxx!!v!!!x                                           x  ",
   "  x                                    xx xxxx xxx       xx xxxxx                                          x  ",
   "  x                                            |     oo                xxxx                                x  ",
   "  x  o                                                                 ssss                                x  ",
   "  x                  xxx             xxxx           xxxx         xxx        e      e       e          e    x  ",
   "  xxxx         oo            xxxx  sx!!!!xxxxx    xx!!!!xxx   xxx!!!xs    =          =      =       =      x  ",
   "  x      x                        sx!!!!!!!!!!xxxx!!!!!!!!!xxx!!!!!!!xs        e      e       e     e      x  ",
   "  x           xxxx               sx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xs    =         =       =        =   x  ",
   "  x                              xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!xs                                  x  ",
   "  x                                    xxx!!!!!!!!!!!!!!!!!!!!!!xxx  xxxx                                  x  ",
   "  x                   xxx     o    |      x!!!!!!!!!!!!!!!!!!!!x                                           x  ",
   "  x                                        x!!!!!!!!!!!!!!xxxxx                                            x  ",
   "  x                          xxx            x!!!!!!!xxxxxxs                                                x  ",
   "  x                         x!!!xxxxx        x!!!!!xsss           xx    xxxxx                              x  ",
   "  x                        x!!!!!!!!!xxx  o   xxxxxs         xxxxx!!xxxx!!!!!x                      o      x  ",
   "  x     e         e      sx!!!!!!!!!!!!!x     sss        xxxx!!!!!!!!!!!!!!!!!x                    ooo     x  ",
   "  x      =        =     sx!!!!!!!!!!!!!!!x            xxx!!!!!!!!!!!!!!!!!!!!!!x                  o o o    x  ",
   "  x             e      sx!!!!!!!!!!!!!!!!!x        xxx!!!xxxxxxx!!!!!!!!xxx!!!!!x                   o      x  ",
   "  x =        =        sx!!!!!!!!!!!!!!!!!!!x  oo  x!!!!!x   =   xx!!!!xx   xx!!!!x                  o      x  ",
   "  x        e         sx!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!x          xxxx   |   xxxxxx                 o      x  ",
   "  x    =         =  sx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                   xxx       x      x  ",
   "  x   e       e    sx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx                                            xxxxx    x  ",
   "  x    =   =      sx!!!!!!!!!!!!!!!!!!!!!!!!!!x         o     xxxxxxxx           xxxxx                     x  ",
   "  x        e     sx!!!!!!!!!!!!!!!!!!!!!!!!!xx              xx!!!!!!!!xxxxx   xxx!!!!!x                  xxx  ",
   "  x   =         sx!!!!!!!!!!!!!!!!!!!!!!!!xx     e         x!!!!!!!!!!!!!!!xxx!!!!!!!!!x                 x x  ",
   "  x             x!!!!!!x!!!!!!!!!!!!!!!!!x              xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                  x  ",
   "  x            xxxxxxxx xx!!!!!!!!!!!!!!x             xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                 x  ",
   "  x                       xxxx!!!!!!!!!x            xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                x  ",
   "  x             o       |     xx!!!!xxx     o    xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        oooo   x  ",
   "  x         x                   xxxx            x!!!!!!!!!!!!!!!!!xxxxxxxxxx!!xxxx!!!!!!!!!!x      oooooo  x  ",
   "  x        x!xxxxxxx                           x!!!!!!!!!!!!!!xxxx          xx    xxxxx!!!!!!x    oooooooo x  ",
   "  x  @    x!!!!!!!!!xxx      o     |          x!!!!!!!!!!!!!!x  ooooooooooo            xxxxxxxx    oooooo  x  ",
   "  x      x!!!!!!!!!!!!!xxxxx              xxxx!!!!!!!!!!!!!!x   ooooooooooo   ooo                   oooo   x  ",
   "  x     x!!!!!!!!!!!!!!!!!!!xxxxx      xxx!!!!!!!!!!!!!!!!!x    ooooooooooo        oo        o             x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                         r    ",
   "                                                                                                              ",
   "                                                                               o                              ",
   "                      x     oo                          o             o                                       ",
   "                                                             xx   s            x   s                   x e x  ",
   "         x       x         xxxx            x           xx    ss   s  xxx   s   s   s  x   x  s  x  s    xxx   ",
   "         x   e   x                   x            x         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "   o                                 x     e      x         xxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "x                                                                                       =                   x ",
   "  xxx                                                                                                         ",
   "          o              x                                                                                    ",
   "                    o                                                                                         ",
   "          x                     x                                                                             ",
   "                    x                                                                                         ",
   "                                      x               oo                                                      ",
   "                x                                     oo        x           |                                 ",
   "x                        e                    x            x    |       x               x       oo            ",
   "                                                      xx                           x                          ",
   "                                                      xx                      xx               xxxx           ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxxxxxxvxxxxxvxxxxxv                ",
   "x   =                                                                                                 xxx     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xx                                                                                                         x",
   "  x                      x               |                                                                    ",
   "  x              x          |                                x                                                ",
   "  x           |                      x          o                        o                                    ",
   "  x                  x   |    x                 o          |     |       o                x                  x",
   "  x  @     x                                x   o       x                o    x     x                x    ooo ",
   "  x                                             o            |      x                           x             ",
   "  xxxxxxx                                     xxxxx                     xxx                              xxxxx",
   "        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                    x       x                          x         x         x                                  ",
   "                     x     x   xxx    x     x           x       x x       x      x     xx       x    x        ",
   "                      x   x   x   x   x     x           x       x x       x      x     x x      x    x        ",
   "                       x x   x     x  x     x            x     x   x     x       x     x  x     x    x        ",
   "                        x    x     x  x     x            x     x   x     x       x     x   x    x    x        ",
   "                        x    x     x  x     x             x   x     x   x        x     x    x   x    x        ",
   "                        x    x     x  x     x             x   x     x   x        x     x     x  x    x        ",
   "                        x     x   x    x   x               x x       x x         x     x      x x             ",
   "                        x      xxx      xxx                 x         x          x     x       xx    x        ",
   "                                                                                                              ",
   "                                                                                                          r   ",
   "                                                                                                              ",
   "   @                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
